spring:
  jpa:
    hibernate:
      ddl-auto: none
  database:
    driver-class-name: org.postgresql.Driver
  datasource:
    url: jdbc:postgresql://localhost:5432/test
    username: test
    password: test
  flyway:
    enabled: true
    table: schema_version

